### ISSUE TITLE
Not compatible with an up to date GHC version

### ISSUE THREAD

**Issue by ghost** [mcschroeder/ctrie#1]
So this sounds exactly like what I was looking for. 
And it looks great.

However its useless, since the package is not compatible with an up to date GHC setup.
It would be great if this can be fixed. Thanks.

Greetings, Jelle

**Comment by mcschroeder** [comment]
(Sorry for the late answer. The holidays etc.)

Yeah, I've let this one collect a little dust... But, I've just loosened the dependency bounds and eliminated some new warnings. It should now build with recent versions of GHC without any problems. The new version is 0.1.0.3 on Hackage, and it should be coming to Stackage in a short while as well.

Thanks for your interest and have a happy new year!
